name: Build and Deploy Static Web App to Azure

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      # Setup Node.js (you may use other versions if required)
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or use the required Node.js version

      # Install dependencies
      - name: 'Install Dependencies'
        run: |
          npm install

      # Build the application (not needed for static HTML, CSS, JS, so this step can be skipped)
      - name: 'Build'
        run: |
          npm run build  # You can skip this step if it's unnecessary (since it's not a complex JavaScript app)

      # Deploy to Azure Static Web Apps
      - name: 'Deploy to Azure Static Web App'
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"  # Root folder for the static content
          api_location: ""  # Leave blank if you don't have a backend API
          output_location: ""  # Leave blank for static HTML files
