name: Build and Deploy Static Web App to Azure

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (needed for static web apps)
      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or use the Node.js version that suits your project

      # Step 3: Install dependencies (only needed if you're using Node.js)
      - name: 'Install Dependencies'
        run: npm install

      # Step 4: Build the application (this step is optional for static HTML, skip if not needed)
      - name: 'Build'
        run: npm run build  # Run the build script if you're using a JS framework like React or Vue.js

      # Step 5: Deploy to Azure Static Web App
      - name: 'Deploy to Azure Static Web App'
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Use the secret here
          app_location: "/"  # Path to your static content ("/" if it's at the root)
          api_location: ""  # Leave empty if no API backend is used
          output_location: ""  # Leave empty for static files (or specify if needed)
