name: Build and Deploy Static Web App to Azure

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (use Node.js 20 for future compatibility)
      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Updated to Node.js 20

      # Step 3: Install dependencies (only needed if you're using Node.js)
      - name: 'Install Dependencies'
        run: npm install

      # Step 4: Build the application (this step is optional for static HTML, skip if not needed)
      - name: 'Build'
        run: npm run build  # Run the build script if you're using a JS framework like Re
